# Generated by Django 5.1.6 on 2025-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
