# Generated by Django 5.1.6 on 2025-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0002_loan_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="monthly_payment",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="paid",
            field=models.IntegerField(default=0),
        ),
    ]
