# Generated by Django 5.1.6 on 2025-02-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0003_loan_monthly_payment_loan_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="paid",
            new_name="paid_month",
        ),
    ]
