# Generated by Django 5.1.6 on 2025-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_rename_paid_loan_paid_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_month',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
