# Generated by Django 5.1.6 on 2025-04-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_not_deleyad',
            new_name='is_not_delayed',
        ),
    ]
