# Generated by Django 5.1.6 on 2026-08-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0012_merge_start_and_bigauto"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="note",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
