# Generated by Django 5.1.6 on 2026-08-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0013_loan_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="transfer",
            name="from_currency",
            field=models.CharField(
                choices=[
                    ("AZN", "₼ AZN"),
                    ("USD", "$ USD"),
                    ("EUR", "€ EUR"),
                    ("CSH", "Available Cash (AZN)"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="to_currency",
            field=models.CharField(
                choices=[
                    ("AZN", "₼ AZN"),
                    ("USD", "$ USD"),
                    ("EUR", "€ EUR"),
                    ("CSH", "Available Cash (AZN)"),
                ],
                max_length=3,
            ),
        ),
    ]
